# Generated by Django 3.2 on 2023-07-18 12:15

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('imagem_empresa', stdimage.models.StdImageField(force_min_size=False, help_text='Imagem usada como icone da empresa', upload_to=core.models.get_file_path, variations={}, verbose_name='icon')),
                ('icone_do_site_icon', stdimage.models.StdImageField(force_min_size=False, help_text='Icone que aparece no navegador ao visitar o site. Formato precisa ser ".icon"', upload_to=core.models.get_file_path, variations={}, verbose_name='icon')),
            ],
            bases=('core.base',),
        ),
    ]
