# Generated by Django 4.1 on 2023-02-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinamentos',
            old_name='sistem',
            new_name='sistema',
        ),
    ]
