# Generated by Django 3.2 on 2023-07-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='status',
            field=models.BooleanField(choices=[(True, 'Aberto'), (False, 'Fechado')], default=True),
        ),
        migrations.DeleteModel(
            name='TreinamentoStatus',
        ),
    ]
