# Generated by Django 3.2 on 2023-07-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0003_alter_treinamentos_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='status',
            field=models.BooleanField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default=True),
        ),
    ]
