# Generated by Django 3.2 on 2023-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0005_alter_treinamentos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Finalizado', 'Finalizado')], default=True, max_length=10),
        ),
    ]
