# Generated by Django 3.2 on 2023-07-25 17:12

import core_api.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_api.base')),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('imagem_empresa', stdimage.models.StdImageField(force_min_size=False, help_text='Imagem usada como icone da empresa', upload_to=core_api.models.get_file_path, variations={}, verbose_name='Imagem da empresa')),
                ('icone_do_site_icon', stdimage.models.StdImageField(force_min_size=False, help_text='Icone que aparece no navegador ao visitar o site. Formato precisa ser ".icon"', upload_to=core_api.models.get_file_path, variations={}, verbose_name='icone da empresa')),
            ],
            options={
                'verbose_name': 'Empregador',
                'verbose_name_plural': 'Empregador',
            },
            bases=('core_api.base',),
        ),
    ]
