# Generated by Django 3.2 on 2023-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario do sistema', 'verbose_name_plural': 'Usuarios do sistema'},
        ),
        migrations.AlterField(
            model_name='permissao',
            name='empresa_cadastro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='empresa_editar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='empresa_visualizar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='treinamento_cadastro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='treinamento_editar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='treinamento_visualizar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='usuario_cadastro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='usuario_editar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='usuario_visualizar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
