# Generated by Django 3.2 on 2023-07-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('razao', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('fantasia', models.CharField(max_length=100)),
                ('nome_adicional', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('observacoes', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Sistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='SistemaQtdFuncionarios',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('quantidade', models.IntegerField()),
                ('contrato', models.CharField(max_length=10)),
                ('suporte', models.CharField(max_length=3)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.sistemas')),
            ],
            options={
                'verbose_name': 'Sistema e quantidade de funcionario',
                'verbose_name_plural': 'Sistemas e quantidades de funcionarios',
            },
            bases=('core.base',),
        ),
    ]
