# Generated by Django 4.1 on 2023-01-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemaqtdfuncionarios',
            name='razao',
        ),
    ]
