# Generated by Django 4.1 on 2023-01-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_sistemaqtdfuncionarios_razao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemaqtdfuncionarios',
            options={'verbose_name': 'Sistema e quantidade de funcionario', 'verbose_name_plural': 'Sistemas e quantidades de funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='sistemas',
            options={'verbose_name': 'Sistema', 'verbose_name_plural': 'Sistemas'},
        ),
    ]
